test Jive

diff --git a/.github/workflows/actions.yml b/.github/workflows/actions.yml
--- a/.github/workflows/actions.yml
+++ b/.github/workflows/actions.yml
@@ -30,9 +30,9 @@ jobs:
     - uses: julia-actions/julia-buildpkg@v1
   # - uses: julia-actions/julia-runtest@v1
 
-    - name: Pkg.develop, Pkg.update, Pkg.status
+    - name: Pkg.develop, Pkg.status
       run: |
-           julia --project=. -e 'using Pkg; Pkg.develop("Jive"); Pkg.update("Jive"); Pkg.status("Jive")'
+           julia -e 'using Pkg; Pkg.develop("Jive"); Pkg.status("Jive")'
 
     - name: ARGS to filter the targets
       run: |
@@ -56,35 +56,36 @@ jobs:
 
     - name: expect_failures
       run: |
-           julia --project=. -e 'using Pkg; Pkg.develop("Jive"); Pkg.status("Jive")'
+           julia -e 'using Pkg; Pkg.develop("Jive"); Pkg.status("Jive")'
            cd test/
            make expect_failures
            cd ../
 
     - name: runtests(; failfast::Bool), JULIA_TEST_FAILFAST
       run: |
-           julia --project=. -e 'using Pkg; Pkg.status("Jive")'
+           julia -e 'using Pkg; Pkg.develop("Jive"); Pkg.status("Jive")'
            cd test/
            echo "########### runtests(; failfast=true)"
-                                 julia --project=..  -e 'using Jive; runtests(@__DIR__, targets="fails", failfast=true)'  && echo "🚨 success" || echo "🟢 failure"
+                                 julia -e 'using Jive; runtests(@__DIR__, targets="fails", failfast=true)'  && echo "🚨 success" || echo "🟢 failure"
 
-           echo "########### JULIA_TEST_FAILFAST=1 runtests(; )"
-           JULIA_TEST_FAILFAST=1 julia --project=..  -e 'using Jive; runtests(@__DIR__, targets="fails")'                 && echo "🚨 success" || echo "🟢 failure"
+           echo "########### JULIA_TESTntests(; )"
+           JULIA_TEST_FAILFAST=1 julia -e 'using Jive; runtests(@__DIR__, targets="fails")'                 && echo "🚨 success" || echo "🟢 failure"
 
-           echo "########### JULIA_TEST_FAILFAST=0 runtests(; failfast=true) # override by JULIA_TEST_FAILFAST"
-           JULIA_TEST_FAILFAST=0 julia --project=..  -e 'using Jive; runtests(@__DIR__, targets="fails", failfast=true)'  && echo "🚨 success" || echo "🟢 failure"
+           echo "########### JULIA_TESTntests(; failfast=true) # override by JULIA_TEST_FAILFAST"
+           JULIA_TEST_FAILFAST=0 julia -e 'using Jive; runtests(@__DIR__, targets="fails", failfast=true)'  && echo "🚨 success" || echo "🟢 failure"
 
-           echo "########### runtests(; ) # failfast=false (default)"
-                                 julia --project=..  -e 'using Jive; runtests(@__DIR__, targets="fails")'                 && echo "🚨 success" || echo "🟢 failure"
+           echo "########### runtests(;false (default)"
+                                 julia -e 'using Jive; runtests(@__DIR__, targets="fails")'                 && echo "🚨 success" || echo "🟢 failure"
 
-           echo "########### runtests(; failfast=true)"
-                                 julia --project=..  -e 'using Jive; runtests(@__DIR__, targets="errors", failfast=true)' && echo "🚨 success" || echo "🟢 failure"
+           echo "########### runtests(;)"
+                                 julia -e 'using Jive; runtests(@__DIR__, targets="errors", failfast=true)' && echo "🚨 success" || echo "🟢 failure"
            cd ../
 
     - name: using Revise
       run: |
            cd test/Example/test/
-           julia --project=.. -e 'using Pkg; Pkg.add("Revise"); Pkg.add("Jive"); Pkg.activate(".."); p1 = @async include("revise.jl"); Timer(3) do t; touch("example/test3.jl"); sleep(0.5); rm("example/test3.jl"); sleep(1); exit(0); end; wait(p1)' example
+           julia --project=.. -e 'using Pkg; Pkg.add("Revise"); Pkg.add("Jive"); Pkg.activate("..")'
+           julia --project=.. -e 'p1 = @async include("revise.jl"); Timer(3) do t; touch("example/test3.jl"); sleep(0.5); rm("example/test3.jl"); sleep(1); exit(0); end; wait(p1)' example
            cd ../../../
 
     - name: runtests(; enable_distributed::Bool), JIVE_PROCS
