set overrides runtests(; targets, failfast)

diff --git a/.github/workflows/actions.yml b/.github/workflows/actions.yml
--- a/.github/workflows/actions.yml
+++ b/.github/workflows/actions.yml
@@ -37,29 +37,41 @@ jobs:
     - name: ARGS to filter the targets
       run: |
            cd test/
-           echo "########### julia runtests.jl jive/runtests/target"
-                           julia --project=.. runtests.jl jive/runtests/target
-           echo "########### julia runtests.jl runtests.jl jive/r  start=2"
-                           julia --project=.. runtests.jl jive/r  start=2
+           echo "########### julia runtests.jl jive/runtests/testset testjive"
+                julia --project=.. runtests.jl jive/runtests/testset testjive
+
+           echo "########### julia runtests.jl testjive jive/runtests/testset"
+                julia --project=.. runtests.jl testjive jive/runtests/testset
+
+           echo "########### julia runtests.jl jive/r start=5"
+                julia --project=.. runtests.jl jive/r start=5
            cd ../
 
     - name: runtests(; skip::Vector{String}), JIVE_SKIP
       run: |
            cd test/
-           echo "########### JIVE_SKIP=Example,errors,fails,jive/onlyonce/heavy.jl,jive/__END__/included.jl,jive/__REPL__ julia runtests.jl"
-                           JIVE_SKIP=Example,errors,fails,jive/onlyonce/heavy.jl,jive/__END__/included.jl,jive/__REPL__ julia --project=.. runtests.jl
+           echo "########### JIVE_SKIP=Example,errors,fails,jive/onlyonce/heavy.jl,jive/__END__/included.jl,jive/__REPL__  julia runtests.jl"
+                             JIVE_SKIP=Example,errors,fails,jive/onlyonce/heavy.jl,jive/__END__/included.jl,jive/__REPL__  julia --project=.. runtests.jl
            cd ../
 
     - name: runtests(; failfast::Bool), JULIA_TEST_FAILFAST
       run: |
            julia --project=. -e 'using Pkg; Pkg.status("Jive")'
            cd test/
-           echo "########### runtests(; failfast=false)"
-                                 julia --project=..  -e 'using Jive; runtests(@__DIR__, targets=["fails"], failfast=false)' || true
            echo "########### runtests(; failfast=true)"
-                                 julia --project=..  -e 'using Jive; runtests(@__DIR__, targets=["fails"], failfast=true)' || true
-           echo "########### JULIA_TEST_FAILFAST=1 julia runtests.jl"
-           JULIA_TEST_FAILFAST=1 julia --project=..  -e 'using Jive; runtests(@__DIR__, targets=["errors"])' || true
+                                 julia --project=..  -e 'using Jive; runtests(@__DIR__, targets="fails", failfast=true)' || true
+
+           echo "########### JULIA_TEST_FAILFAST=1 runtests(; )"
+           JULIA_TEST_FAILFAST=1 julia --project=..  -e 'using Jive; runtests(@__DIR__, targets="fails")' || true
+
+           echo "########### JULIA_TEST_FAILFAST=0 runtests(; failfast=true) # override by JULIA_TEST_FAILFAST"
+           JULIA_TEST_FAILFAST=0 julia --project=..  -e 'using Jive; runtests(@__DIR__, targets="fails", failfast=true)' || true
+
+           echo "########### runtests(; ) # failfast=false (default)"
+                                 julia --project=..  -e 'using Jive; runtests(@__DIR__, targets="fails")' || true
+
+           echo "########### runtests(; failfast=true)"
+                                 julia --project=..  -e 'using Jive; runtests(@__DIR__, targets="errors", failfast=true)' || true
            cd ../
 
     - name: using Revise
@@ -75,10 +87,13 @@ jobs:
            cd test/
            echo "########### julia -pauto runtests.jl"
                            julia --project=.. -pauto -e 'using Jive; runtests(@__DIR__, targets=["test"])'
+
            echo "########### julia -pauto runtests(; enable_distributed=false)"
                            julia --project=.. -pauto -e 'using Jive; runtests(@__DIR__, targets=["test"], enable_distributed=false)'
+
            echo "########### JIVE_PROCS=auto julia runtests.jl"
            JIVE_PROCS=auto julia --project=..        -e 'using Pkg; Pkg.test(; test_args=["test"])'
+
            echo "########### JIVE_PROCS=0 julia -pauto runtests.jl"
            JIVE_PROCS=0    julia --project=.. -pauto -e 'using Pkg; Pkg.test(; test_args=["test"])'
            cd ../
